version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: 192.168.99.100:9200





# docker run -d --link es01:elasticsearch -p 5601:5601 docker.elastic.co/kibana/kibana:7.5.2
